# Ansible resource block for Azure SQL db
---
- hosts: localhost
  tasks:
  - name: Prepare random postfix
    set_fact: 
     rpfx: "{{1000 | random}}"
    run_once: yes 
- hosts: localhost
  vars:
   resource_group: "{{resource_group_name}}"
   location: "southeast asia"
   sqlserver_name: sqlansibledemo{{ repx }} 
   sqldb_name: "{{sqldbname}}"
   admin_username: "{{admin_username}}"
   admin_password: "{{admin_password}}"
  tasks:
   - name:  create a resource group
     azure_rm_resourcegroup: 
      name: "{{resource_group}}"
      location: "{{location}}"
   - name: Create Azure SQL server
     azure_rm_sqlserver:  
      name: "{{sqlserver_name}}"
      resource_group: "{{resource_group}}"
      version: 12.0
      admin_username: "{{admin_username}}"
      admin_password: "{{admin_password}}"
   - name: Create instance of SQL database
     azure_rm_sqldatabase:
      resource_group: "{{resource_group}}"
      server_name: "{{sqlserver_name}}"
      name: "{{sqldb_name}}"    