#Ansible block for Azure VM with VNET creation
---
- hosts: localhost
  connection: local
  name: Provision Azure VM 
  vars: 
   resource_group: "{{ resource_group_name }}"
   vm_name: "demovm"
   location: "southeast asia"
   admin_username: "{{ admin_username }}"
   admin_password: "{{ admin_password }}"
  tasks: 
  - name: Create a resource group
    azure_rm_resourcegroup:
     name: "{{ resource_group }}"
     location: "{{ location }}"
  - name: Provision Azure Virtual Network
    azure_rm_virtualnetwork: 
     resource_group: "{{ resource_group }}"
     name: "{{ vm_name }}"
     address_prefixes: "10.0.0.0/16"
  - name: Adding Subnet to Vnet
    azure_rm_subnet: 
     resource_group: "{{ resource_group }}"
     name: "{{ vm_name }}"
     address_prefix: "10.0.1.0/24"
     virtual_network: "{{ vm_name }}"
  - name: Provision a Public IP address
    azure_rm_publicipaddress: 
     resource_group: "{{ resource_group }}"
     allocated_method: static
  - name: Provision a network security group (nsg) with allows SSH
    azure_rm_securitygroup:
     name: "{{ vm_name }}"
     rules: 
     - name: SSH
       protocol: TCP
       destination_port_range: 22 
       access: Allow 
       priority: 1001
       direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
     resource_group: "{{ resource_group }}"
     name: "{{ vm_name }}"
     virtual_network: "{{ vm_name }}"
     subnet: "{{ vm_name }}"
     public_ip_name: "{{ vm_name }}"
     security_group: "{{ vm_name }}"
  - name: Provision VM
    azure_rm_virtualmachine:
     resource_group: "{{ resource_group }}"
     name: "{{ vm_name }}"
     vm_size: "{{ vm_size }}"
     admin_username: "{{ admin_username }}"
     admin_password: "{{ admin_password }}"
     network_interfaces: "{{ vm_name }}"
     image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 18.04-LTS
      version: latest    






